--- #YAML:1.0
name:               Test-Given
version:            0.3.0
abstract:           Given/When/Then style testing for Perl.
author:
    - Robert Juliano <rovjuvano@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    parent:   0
    version:  0.77
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
